- name: restart kubelet
  service:
    name: kubelet
    state: restarted

- name: kill kubeapi
  command: killall kube-apiserver
  ignore_errors: yes
  listen: "restart kubeapi"

- name: restart kubelet to restart kubeapi
  service:
    name: kubelet
    state: restarted
  listen: "restart kubeapi"

- name: wait kubeapi port
  wait_for:
    port: 8080
  listen: "restart kubeapi"
